const Router = require('koa-router')
const router = new Router()
const user = require('./controller/user')

router.post('/blog/register', user.register)
router.post('/blog/login', user.login)
router.post('/blog/sendEdit',user.sendEdit)
router.post('/blog/getBlog',user.getBlog)
router.post('/blog/enterBlog',user.enterBlog)
router.post('/blog/PersonalInfoChange',user.PersonalInfoChange)
router.post('/blog/memoryLogin',user.memoryLogin)
router.post('/blog/uploadAvator',user.uploadAvator)
router.post('/blog/uploadAvatorValid',user.uploadAvatorValid)
router.post('/blog/getNewAvator',user.getNewAvator)
router.post('/blog/checkExistAccount',user.checkExistAccount)
router.post('/blog/sendComment',user.sendComment)
router.post('/blog/getComment',user.getComment)
router.post('/blog/deleteComment',user.deleteComment)
router.post('/blog/personalGetBlog',user.personalGetBlog)
router.post('/blog/findDataByName',user.findDataByName)
router.post('/blog/handleBlogDelete',user.handleBlogDelete)
router.post('/blog/updateArticle',user.updateArticle)
router.post('/blog/uploadBlogPhoto',user.uploadBlogPhoto)
module.exports = router